// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useAppConfig: () => import('nuxt/schema').AppConfig
  const defineAppConfig: <C extends import('nuxt/schema').AppConfigInput>(config: C) => C
  const createError: typeof import('h3')['createError']
  const setResponseStatus: typeof import('h3')['setResponseStatus']
  const blogReadMinutes: typeof import('../../shared/utils/blogs').blogReadMinutes
  const blogWordCount: typeof import('../../shared/utils/blogs').blogWordCount
  const blogs: typeof import('../../shared/utils/blogs').blogs
  const caseStudies: typeof import('../../shared/utils/caseStudies').caseStudies
  const caseStudyWordCount: typeof import('../../shared/utils/caseStudies').caseStudyWordCount
  const getBlogBySlug: typeof import('../../shared/utils/blogs').getBlogBySlug
  const getCaseStudyBySlug: typeof import('../../shared/utils/caseStudies').getCaseStudyBySlug
  const getTagIcon: typeof import('../../shared/utils/icons').getTagIcon
  const projects: typeof import('../../shared/utils/projects').projects
  const sitePaths: typeof import('../../shared/utils/site').sitePaths
  const siteUrl: typeof import('../../shared/utils/site').siteUrl
  const sitemapEntries: typeof import('../../shared/utils/sitemap').sitemapEntries
  const tagIconMap: typeof import('../../shared/utils/icons').tagIconMap
}
// for type re-export
declare global {
  // @ts-ignore
  export type { BlogBlock, BlogEntity, BlogPost } from '../../shared/utils/blogs'
  import('../../shared/utils/blogs')
  // @ts-ignore
  export type { CaseBuiltItem, CaseIncident, CaseDecision, CaseNote, CaseStudy } from '../../shared/utils/caseStudies'
  import('../../shared/utils/caseStudies')
  // @ts-ignore
  export type { IProject } from '../../shared/utils/projects'
  import('../../shared/utils/projects')
}