/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutCV: typeof import('./src/components/cv/aboutCV.vue')['default']
    Aboutme: typeof import('./src/components/aboutme.vue')['default']
    BackGround: typeof import('./src/components/BackGround.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    HeaderCV: typeof import('./src/components/cv/headerCV.vue')['default']
    ModelView: typeof import('./src/components/modelView.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Old: typeof import('./src/components/old.vue')['default']
    ProjectModel: typeof import('./src/components/projectModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Songs: typeof import('./src/components/songs.vue')['default']
  }
}
