const lesoll = '/projects/lesoll-logo.png'
const egystay = '/projects/egy-stay-logo.png'
const Qars = '/projects/Qar.png'
const Gosha0 = '/projects/0Gosha.png'
const GenImport = '/projects/Gen-Import.jpg'
const srvj = '/projects/srvj.png'

export interface IProject {
  id: number
  name: string
  slug: string
  category: string
  logoWidth?: number
  logoHeight?: number
  logo?: string
  class?: string
  link?: string
  github?: string
  npm?: string
  caseStudy?: boolean
  tagline?: string
  altNames?: string[]
  desc: string | string[]
  tags: string | string[]
  keywords?: string | string[]
  metaDescription?: string | string[]
}

export const projects: IProject[] = [
  {
    id: 1,
    name: "Lesoll",
    slug: "lesoll",
    category: "Live",
    caseStudy: true,
    logo: lesoll,
    logoWidth: 96,
    logoHeight: 96,
    link: "https://lesoll.com",
    class: "w-5 h-auto",
    github: "",
    tagline: "Production B2B/B2C real-estate & automotive marketplace backend",
    altNames: ["Lesoll.com", "Lesoll Egypt", "Lesoll Real Estate", "ليسول"],
    desc: [
      "Lesoll is a large-scale classifieds marketplace for the Egyptian real estate market, enabling users to buy, sell, and rent residential, commercial, land, and compound properties.",
      "The platform includes premium listing packages, real-time messaging, a blog, and a complete internal administration system.",
      "As the primary Backend Engineer, I designed and implemented core backend services, REST APIs, business logic, database architecture, third-party integrations, and performance optimizations.",
      "I owned 100% of the backend implementation, building and maintaining features across the listing lifecycle, authentication, payments, notifications, search, analytics, and internal admin services while supporting a production platform serving real users."
    ],
    tags: [
      "Typescript",
      "Javascript",
      "Express.js",
      "MongoDB",
      "Paymob (Payment Gateway)",
      "Resend",
      "BullMQ",
      "Redis",
      "Puppeteer",
      "Swagger",
      "Docker",
      "AWS (S3, EC2, CloudFront, Route 53)",
      "Socket.IO",
      "NGINX",
      "pm2",
      "pnpm",
      "git/github",
      "Github Actions"
    ],
    keywords: [
      "Lesoll",
      "Lesoll Marketplace",
      "Real Estate Marketplace",
      "Automotive Marketplace",
      "Property Listing Platform",
      "Car Marketplace",
      "B2B Marketplace",
      "B2C Marketplace",
      "Marketplace Backend",
      "Marketplace API",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Redis",
      "BullMQ",
      "Paymob",
      "Payment Gateway Integration",
      "OTP Authentication",
      "SMS Verification",
      "Email Notifications",
      "Real-time Chat",
      "Socket.IO",
      "Admin Dashboard",
      "User Dashboard",
      "Notification System",
      "Puppeteer Web Scraping",
      "Background Jobs",
      "Docker",
      "NGINX",
      "AWS EC2",
      "AWS S3",
      "AWS CloudFront",
      "AWS Route 53",
      "AWS SQS",
      "GitHub Actions",
      "CI/CD",
      "REST API",
      "Backend Architecture",
      "Production Backend",
      "Scalable Backend",
      "Cloud Deployment"
    ],
    metaDescription:
      "Technical case study of Lesoll, a production B2B and B2C real estate and automotive marketplace. Explore its Express.js backend, MongoDB, Redis, BullMQ, Paymob integration, Docker deployment, AWS infrastructure, real-time chat, notifications, and scalable backend architecture."
  },
  {
    id: 2,
    name: "EgyStay",
    slug: "egystay",
    category: "Live",
    caseStudy: true,
    logo: egystay,
    logoWidth: 73,
    logoHeight: 19,
    class: "w-5 h-auto",
    link: "https://egystay.com",
    github: "",
    tagline: "Property rental & booking platform with a Co-Host marketplace",
    altNames: ["EgyStay", "EGYStay", "Egy Stay", "EgyStay.com", "إيجي ستاي", "ايجي ستاي"],
    desc: [
      "EgyStay is a short-term rental platform for the Egyptian market, allowing guests to book accommodations while hosts and co-hosts manage their properties through dedicated dashboards.",
      "As the primary Backend Engineer, I architected and developed the backend from the ground up, implementing reservation workflows, availability management, pricing logic, payments, authentication, messaging, notifications, and administrative services.",
      "I contributed approximately 80% of the project's implementation (1100 of 1300 commits), delivering around 63,000 lines of production code across 600+ source files while focusing on scalability, maintainability, and performance."
    ],
    tags: [
      "Typescript",
      "Express.js",
      "MongoDB",
      "Amazon Payment Service (APS)",
      "Paymob",
      "Resend",
      "BullMQ",
      "Redis",
      "Swagger",
      "Docker",
      "AWS (S3, EC2, CloudFront, Route 53)",
      "Socket.IO",
      "Axios",
      "NGINX",
      "pm2",
      "pnpm",
      "git/github",
      "Github Actions"
    ],
    keywords: [
      "EgyStay",
      "EGYStay",
      "EgyStay Booking Platform",
      "Property Rental Platform",
      "Vacation Rental Platform",
      "Property Booking System",
      "Hotel Booking Alternative",
      "Short-Term Rental Platform",
      "Rental Marketplace",
      "Booking Engine",
      "Reservation System",
      "Co-Host Management",
      "Property Management",
      "Cancellation Policy",
      "Marketplace Backend",
      "Booking Platform Backend",
      "TypeScript",
      "Node.js",
      "Express.js",
      "Modular Monolith Architecture",
      "MongoDB",
      "Redis",
      "BullMQ",
      "Amazon Payment Services",
      "APS Payment Gateway",
      "Payment Gateway Integration",
      "OTP Authentication",
      "SMS Verification",
      "Email Notifications",
      "Real-time Chat",
      "Socket.IO",
      "Admin Dashboard",
      "Host Dashboard",
      "User Dashboard",
      "Notification System",
      "Background Jobs",
      "Puppeteer Web Scraping",
      "Docker",
      "NGINX",
      "AWS EC2",
      "AWS EKS",
      "AWS S3",
      "AWS CloudFront",
      "AWS Route 53",
      "AWS SQS",
      "GitHub Actions",
      "CI/CD",
      "REST API",
      "Scalable Backend",
      "Production Backend",
      "Cloud Deployment"
    ],
    metaDescription:
      "Technical case study of EgyStay, a production property rental and booking platform. Discover its Express.js backend, MongoDB, Amazon Payment Services (APS) integration, booking engine, Co-Host system, BullMQ, Docker, AWS EKS deployment, and scalable backend architecture."
  },
  {
    id: 3,
    name: "SRVJ",
    slug: "srvj",
    category: "Live",
    caseStudy: true,
    logo: srvj,
    logoWidth: 96,
    logoHeight: 96,
    class: "w-5 h-5",
    link: "https://srvj.elrefai.me/",
    github: "",
    tagline: "Real-time collaborative diagram editor built on Yjs CRDTs",
    desc: [
      "Built real-time collaborative diagram editing using Yjs CRDTs over a custom WebSocket server implementing the Yjs sync and awareness protocols, enabling live cursors, presence, and seamless multiplayer editing.",
      "Secured WebSocket connections with PASETO v4 authentication and enforced project-level role-based access control, while isolating collaboration sessions into dedicated board rooms.",
      "Designed a dual-snapshot persistence layer that stores both the authoritative Yjs binary state for lossless recovery and a denormalized JSON representation for efficient querying and API reads.",
      "Architected the backend using PostgreSQL/Prisma for relational data (users, projects, memberships, sharing) and MongoDB/Mongoose for high-frequency diagram mutations.",
      "Implemented horizontally scalable notifications using SSE with Redis Pub/Sub fan-out, alongside BullMQ workers for asynchronous email and notification processing.",
      "Improved platform reliability and security through Zod validation, Helmet, CORS, rate limiting, centralized error handling, structured logging with Pino, and Prometheus metrics. Verified collaboration behavior with integration tests and containerized the platform using Docker Compose behind Nginx."
    ],
    tags: [
      "TypeScript",
      "Express",
      "PostgreSQL",
      "Prisma",
      "MongoDB",
      "Redis",
      "BullMQ",
      "Docker",
      "Kubernetes",
      "NGINX",
      "Socket.IO",
      "CRDTs (Yjs)",
      "Cloudinary",
      "Vitest",
      "Vue.js",
      "Vite",
      "Vue Flow",
      "Pinia",
      "UnoCSS",
      "Iconify",
      "Github Actions",
      "git/github",
      "PNPM"
    ],
    keywords: [
      "SRVJ",
      "Real-time collaborative editor",
      "Collaborative diagram editor",
      "Multiplayer diagram editor",
      "Yjs",
      "CRDT",
      "Conflict-free Replicated Data Types",
      "Real-time synchronization",
      "Server-Sent Events",
      "SSE",
      "Socket.IO",
      "Express.js",
      "TypeScript",
      "Node.js",
      "Monolithic Modular Architecture",
      "MongoDB",
      "PostgreSQL",
      "Prisma",
      "Redis",
      "BullMQ",
      "Docker",
      "Kubernetes",
      "NGINX",
      "AWS EC2",
      "AWS S3",
      "AWS CloudFront",
      "AWS Route 53",
      "GitHub Actions",
      "Vitest",
      "Vue.js",
      "Vue Flow",
      "Vite",
      "Pinia",
      "UnoCSS",
      "Role-Based Access Control",
      "RBAC",
      "PASETO",
      "WebSocket Authentication",
      "Backend Architecture",
      "Distributed Systems",
      "Real-time Backend",
      "Collaborative Software"
    ],
    metaDescription:
      "Technical case study of SRVJ, a real-time collaborative diagram editor built with Yjs CRDTs, Express.js, PostgreSQL, MongoDB, Redis, SSE, Docker, and Kubernetes. Learn about multiplayer synchronization, WebSocket authentication, dual-snapshot persistence, and scalable backend architecture."
  },
  {
    id: 4,
    name: "Gen Import",
    slug: "gen-import",
    category: "Package",
    logo: GenImport,
    logoWidth: 95,
    logoHeight: 96,
    class: "w-5 h-5",
    github: "https://github.com/elrefai99/Gen-Import",
    npm: "https://www.npmjs.com/package/gen-import",
    tagline: "Automatically generate TypeScript/JavaScript barrel files using the TypeScript compiler API",
    desc: [
      "Builds a full module dependency graph (static imports, `export *`, dynamic `import()`, `require()`, class heritage, decorators) and detects circular dependencies",
      "Classifies the barrel itself as safe / type-safe / ordered / unsafe, and explains exactly which line breaks it at runtime",
      "Sorts files topologically so the barrel import order is safe for CommonJS",
      "Optionally emits lazy (getter-based) re-exports so the barrel itself never causes a circular-require crash",
      "Detects export name collisions across source files",
      "Diffs against the previous barrel to report newly added exports",
      "Prints diagnostics (with fix suggestions), a summary box, and an import/export graph, using `boxen` + `chalk`"
    ],
    tags: [
      "TypeScript",
      "Express",
      "pnpm",
      "git/github",
      "Github Actions",
      "fs"
    ],
    keywords: [
      "Gen Import",
      "gen-import",
      "TypeScript Barrel File Generator",
      "Barrel File",
      "TypeScript Compiler API",
      "npm Package",
      "Node.js CLI",
      "Topological Sort",
      "Cycle Detection",
      "Developer Tooling",
      "TypeScript",
      "Express"
    ],
    metaDescription:
      "Gen Import is an npm package that generates TypeScript/JavaScript barrel files for Express/Node projects using the TypeScript compiler API, with cycle detection, topological sort, and a globals mode."
  },
  {
    id: 6,
    name: "Qar",
    slug: "Qar",
    category: "Live",
    logo: Qars,
    logoWidth: 96,
    logoHeight: 82,
    class: "w-5 h-5",
    link: "https://Qar.elrefai.me/",
    github: "",
    tagline: "Lightweight schedule & task management web app",
    desc: "A lightweight schedule management web app built for organizing daily tasks and dates in a simple, clean interface. The application is deployed on Vercel, providing fast loading, automatic deployments, and reliable hosting for modern web projects.",
    tags: [
      "TypeScript",
      "Vue.js",
      "Vite",
      "Firebase Authentication",
      "Cloud Firestore",
      "Vercel",
      "Responsive Design",
      "Task Management",
      "Schedule Management",
      "Productivity",
      "GitHub"
    ],
    keywords: [
      "Qars",
      "Qars Task Manager",
      "Task Management App",
      "Task Management System",
      "Schedule Management",
      "Daily Planner",
      "Productivity App",
      "To-Do Application",
      "Personal Task Manager",
      "Task Tracking",
      "Calendar Application",
      "Vue.js",
      "TypeScript",
      "Vite",
      "Firebase",
      "Firebase Authentication",
      "Cloud Firestore",
      "Real-time Database",
      "Vercel",
      "Responsive Web App",
      "Single Page Application",
      "Frontend Architecture",
      "Modern Web Application",
      "Progressive Web App",
      "GitHub",
      "CI/CD",
      "Cloud Deployment"
    ],
    metaDescription:
      "Technical case study of Qars, a lightweight task and schedule management application built with Vue.js, TypeScript, Firebase, and Vercel. Explore its architecture, implementation, and deployment decisions."
  },
  {
    id: 5,
    name: "data-localizer",
    slug: "data-localizer",
    category: "Backend",
    class: "w-5 h-5",
    github: "https://github.com/elrefai99/data-localizer",
    npm: "https://www.npmjs.com/package/data-localizer",
    tagline: "A simple utility to localize JSON data fields between ar/en based on headers.",
    desc: [
      "A lightweight TypeScript library for recursively localizing API response data based on the Accept-Language header.",
      "data-localizer automatically detects translation objects inside nested data structures and resolves the best available language using Accept-Language negotiation, fallback languages, and configurable missing-translation behavior.",
      "Recursive localization of nested objects and arrays",
      "Accept-Language parsing with quality (q) values",
      "Automatic translation-object detection",
      "Configurable fallback language chains",
      "Configurable behavior for missing translations",
      "Fully typed with TypeScript",
      "Framework adapters for Express, Fastify, and NestJS",
      "Works with plain objects, arrays, and API response structures"
    ],
    tags: [
      "Go",
      "TypeScript",
      "Javascript",
      "Express.js",
      "Nest.js",
      "git/github",
      "Github Actions"
    ],
    keywords: [
      "Data Localization",
      "API Localization",
      "TypeScript Localization",
      "Node.js Localization",
      "Accept-Language",
      "i18n",
      "Internationalization",
      "Localization",
      "Translation",
      "Recursive Localization",
      "Multilingual API",
      "API Response Localization",
      "Language Negotiation",
      "Locale Negotiation",
      "Translation Fallback",
      "Fallback Languages",
      "Nested Object Localization",
      "JSON Localization",
      "Express.js",
      "Fastify",
      "NestJS",
      "TypeScript",
      "Node.js",
      "Backend Library",
      "Developer Tool"
    ],
    metaDescription:
      "Technical case study of 0Gosha, a self-contained rule-based prompt-optimization engine that rewrites raw text into structured LLM prompts and learns from feedback — built with TypeScript, Express.js, MongoDB, Redis, and BullMQ, with no external AI API calls."
  },
  {
    id: 7,
    name: "Leoxy",
    slug: "leoxy",
    category: "Backend",
    github: "https://github.com/elrefai99/Leoxy",
    tagline: "Leoxy is a lightweight HTTP reverse proxy built in Go. It routes incoming requests to configurable upstream servers based on path prefixes, with built-in health-check endpoints and request logging.",
    desc: [
      "Reverse proxy – forwards requests to multiple backend services using httputil.ReverseProxy.",
      "Path-based routing – each upstream is mapped to a configurable path prefix; the prefix is stripped before forwarding.",
      "Health checks – exposes liveness and ping endpoints for monitoring.",
      "Request logging – logs method, path, remote address, and latency for every request.",
      "CLI – start, stop, and run the service as a background process with cobra-based subcommands.",
      "YAML configuration – upstreams and server settings are defined in leoxy/config.yaml via viper.",
      "Timeouts – explicit read/write/idle timeouts and max header size for safety."
    ],
    tags: [
      "Go",
      "git/github"
    ],
    keywords: [
      "Leoxy",
      "Open Source",
      "GitHub"
    ],
    metaDescription:
      "Leoxy is an open-source project by Mohammed Mostafa. Explore its implementation, documentation, and development history on GitHub."
  },
  {
    id: 8,
    name: "Elrecord",
    slug: "elrecord",
    category: "Backend",
    github: "https://github.com/elrefai99/elrecord",
    tagline: "Scalable real-time chat backend inspired by Discord",
    desc: "Elrecord is a powerful, scalable backend for a real-time chat application inspired by Discord. It supports direct messaging, group chats, and server-based communities with voice/video call capabilities.",
    tags: [
      "TypeScript",
      "Express.js",
      "PostgreSQL",
      "Prisma",
      "Amazon Payment Service (APS)",
      "Message Queue (BullMQ)",
      "Swagger",
      "Redis",
      "Socket.IO",
      "Docker",
      "AWS S3",
      "NGINX",
      "pm2",
      "pnpm",
      "git/github",
    ],
    keywords: [
      "Elrecord",
      "Discord Clone Backend",
      "Real-time Chat Backend",
      "Chat Application Backend",
      "Direct Messaging",
      "Group Chat",
      "Voice and Video Calls",
      "WebSocket Chat",
      "TypeScript",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Prisma",
      "Redis",
      "Socket.IO",
      "BullMQ",
      "Docker",
      "Scalable Backend",
      "Real-time Backend"
    ],
    metaDescription:
      "Technical case study of Elrecord, a scalable real-time chat backend inspired by Discord with direct messaging, group chats, communities, and voice/video calls — built with TypeScript, Express.js, PostgreSQL/Prisma, Redis, and Socket.IO."
  },
]
