<script setup lang="ts">
import { computed } from 'vue'
import { getTagIcon } from '~~/shared/utils/icons'
import { tagIconSymbolId } from '~~/shared/utils/tagIconId'

// References the shared external sprite (public/icons/tags.svg, generated by
// scripts/gen-tag-icons.mjs). Only the tag→id map travels in the JS bundle;
// the artwork is a single cached request made off the critical path, and pages
// with no chips never fetch it.
//
// Renders nothing for an unmapped tag, so callers don't need a v-if.
const props = defineProps<{ tag: string; size?: string }>()

const symbolId = computed(() => {
  const id = getTagIcon(props.tag)
  return id ? tagIconSymbolId(id) : undefined
})
</script>

<template>
  <svg
    v-if="symbolId"
    :class="size ?? 'h-3.5 w-3.5'"
    class="shrink-0"
    aria-hidden="true"
    focusable="false"
  >
    <use :href="`/icons/tags.svg#${symbolId}`" />
  </svg>
</template>
