export type BlogBlock =
  | {
    type: 'paragraph'
    text: string
  }
  | {
    type: 'heading'
    text: string
  }
  | {
    type: 'list'
    items: string[]
  }
  | {
    type: 'code'
    language: string
    filename?: string
    code: string
  }

export type BlogPost = {
  id: number
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  tags: string[]
  blocks: BlogBlock[]
}

export const blogs: BlogPost[] = [
  {
    id: 3,
    slug: 'server-sent-events-real-time-notifications-srvj',
    title: 'Server-Sent Events (SSE): Real-Time Notifications in SRVJ',
    excerpt:
      'How SRVJ delivers real-time notifications with Server-Sent Events, BullMQ, Redis Pub/Sub, and PostgreSQL — a persist-then-fan-out pipeline that scales horizontally without sticky sessions.',
    category: 'Backend Architecture',
    date: '2026-06-27',
    readTime: '9 min read',
    tags: ['SSE', 'Server-Sent Events', 'Real-Time', 'BullMQ', 'Redis', 'PostgreSQL', 'Node.js', 'System Design'],
    blocks: [
      {
        type: 'paragraph',
        text: 'Before diving into SSE, here\'s a quick overview of SRVJ.',
      },
      {
        type: 'paragraph',
        text: 'SRVJ is a side project I\'ve been building to explore and experiment with different technologies and architectural patterns. Inspired by tools like Miro, the project focuses on real-time collaboration and serves as a playground for learning, validating ideas, and gaining hands-on experience with modern backend technologies.',
      },
      {
        type: 'paragraph',
        text: 'Through SRVJ, I\'ve been experimenting with technologies such as:',
      },
      {
        type: 'list',
        items: [
          'CRDTs & Yjs',
          'Server-Sent Events (SSE)',
          'Socket.IO / WebSockets',
          'Docker',
          'Kubernetes',
          'PostgreSQL & MongoDB',
          'Background processing with BullMQ',
        ],
      },
      {
        type: 'paragraph',
        text: 'This post is the first in a series where I\'ll share some of the technical decisions behind the project, starting with Server-Sent Events (SSE).',
      },
      {
        type: 'heading',
        text: 'What is SSE?',
      },
      {
        type: 'paragraph',
        text: 'Server-Sent Events (SSE) is an HTTP-based technology that enables servers to push updates to connected clients over a long-lived connection.',
      },
      {
        type: 'paragraph',
        text: 'Unlike WebSockets, communication is one-way: server → client.',
      },
      {
        type: 'paragraph',
        text: 'Browsers provide native support through the EventSource API, which makes the client implementation straightforward.',
      },
      {
        type: 'heading',
        text: 'Why SSE?',
      },
      {
        type: 'paragraph',
        text: 'Not every real-time feature requires bidirectional communication.',
      },
      {
        type: 'paragraph',
        text: 'In SRVJ, collaborative editing relies on WebSockets because users continuously exchange document updates. Notifications, however, are different: clients only need to receive events generated by the server.',
      },
      {
        type: 'paragraph',
        text: 'For this specific use case, Server-Sent Events (SSE) turned out to be a great fit.',
      },
      {
        type: 'heading',
        text: 'Notification Architecture',
      },
      {
        type: 'paragraph',
        text: 'The notification pipeline in SRVJ is intentionally asynchronous.',
      },
      {
        type: 'list',
        items: [
          'A domain event occurs (board invitation, chat message, etc.).',
          'A BullMQ job is created.',
          'A worker processes the job.',
          'The notification is persisted in PostgreSQL.',
          'The worker publishes the event to Redis Pub/Sub.',
          'The application instance that owns the user\'s SSE connection delivers the notification instantly.',
        ],
      },
      {
        type: 'paragraph',
        text: 'This architecture decouples notification generation from delivery and allows the system to scale horizontally.',
      },
      {
        type: 'heading',
        text: 'Opening the SSE Stream',
      },
      {
        type: 'paragraph',
        text: 'Every authenticated user establishes a long-lived HTTP connection to /stream.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'sse.stream.ts',
        code:
          'res.writeHead(200, {\n' +
          '  "Content-Type": "text/event-stream",\n' +
          '  "Cache-Control": "no-cache",\n' +
          '  Connection: "keep-alive",\n' +
          '  "X-Accel-Buffering": "no",\n' +
          '});\n' +
          'res.flushHeaders?.();',
      },
      {
        type: 'paragraph',
        text: 'Why these headers?',
      },
      {
        type: 'list',
        items: [
          'Content-Type: text/event-stream — Tells the browser that this endpoint will continuously stream events rather than returning a traditional HTTP response.',
          'Cache-Control: no-cache — Prevents intermediaries and browsers from caching streamed events.',
          'Connection: keep-alive — Keeps the HTTP connection open for future events.',
          'X-Accel-Buffering: no — Disables buffering in Nginx. Without this header, notifications may be delayed because Nginx could buffer responses before sending them to clients.',
        ],
      },
      {
        type: 'heading',
        text: 'Managing Active Connections',
      },
      {
        type: 'paragraph',
        text: 'SRVJ allows the same user to be connected from multiple browser tabs or devices simultaneously.',
      },
      {
        type: 'paragraph',
        text: 'To support this behavior, active connections are stored using:',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'sse.connections.ts',
        code:
          'const client: SSEClient = { userId, res };\n' +
          'let connections = clients.get(userId);\n' +
          'if (!connections) {\n' +
          '  connections = new Set<SSEClient>();\n' +
          '  clients.set(userId, connections);\n' +
          '}\n' +
          'connections.add(client);',
      },
      {
        type: 'paragraph',
        text: 'Internally, the structure looks like:',
      },
      {
        type: 'code',
        language: 'ts',
        code: 'Map<userId, Set<SSEClient>>',
      },
      {
        type: 'paragraph',
        text: 'Why use this structure?',
      },
      {
        type: 'paragraph',
        text: 'Using a Map provides constant-time lookup for all active connections belonging to a user.',
      },
      {
        type: 'paragraph',
        text: 'Using a Set allows:',
      },
      {
        type: 'list',
        items: [
          'Multiple tabs per user.',
          'Multiple devices per user.',
          'Efficient connection removal.',
          'Prevention of duplicate connections.',
        ],
      },
      {
        type: 'paragraph',
        text: 'As a result, a user receives notifications across every active session.',
      },
      {
        type: 'heading',
        text: 'Immediately Opening the Stream',
      },
      {
        type: 'paragraph',
        text: 'After the connection is registered, the server immediately writes an empty event:',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'sse.stream.ts',
        code: 'res.write(`: connected\\n\\n`);',
      },
      {
        type: 'paragraph',
        text: 'Why?',
      },
      {
        type: 'paragraph',
        text: 'This comment frame forces the connection to become active immediately so the browser fires the onopen event without waiting for the first notification.',
      },
      {
        type: 'heading',
        text: 'Cleaning Up Disconnected Clients',
      },
      {
        type: 'paragraph',
        text: 'Because SSE connections are long-lived, proper cleanup is essential.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'sse.cleanup.ts',
        code:
          'req.on("close", () => {\n' +
          '  connections!.delete(client);\n' +
          '  if (connections!.size === 0) {\n' +
          '    clients.delete(userId);\n' +
          '  }\n' +
          '});',
      },
      {
        type: 'paragraph',
        text: 'Why?',
      },
      {
        type: 'paragraph',
        text: 'Without cleanup:',
      },
      {
        type: 'list',
        items: [
          'Memory usage would continuously grow.',
          'Dead connections would remain in memory.',
          'The server would attempt to write to closed responses.',
        ],
      },
      {
        type: 'paragraph',
        text: 'Removing stale connections prevents memory leaks.',
      },
      {
        type: 'heading',
        text: 'Redis as the Distribution Layer',
      },
      {
        type: 'paragraph',
        text: 'SRVJ may run on multiple application instances.',
      },
      {
        type: 'paragraph',
        text: 'For example:',
      },
      {
        type: 'list',
        items: [
          'Instance A → User 1 connected',
          'Instance B → User 2 connected',
          'Instance C → Worker running',
        ],
      },
      {
        type: 'paragraph',
        text: 'A worker should not need to know which instance owns a user\'s SSE connection.',
      },
      {
        type: 'paragraph',
        text: 'To solve this problem, Redis Pub/Sub acts as the distribution layer.',
      },
      {
        type: 'paragraph',
        text: 'First, two Redis clients are created:',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'redis.ts',
        code:
          'export const redis = createClient({ url });\n' +
          'export const subscriber = redis.duplicate();',
      },
      {
        type: 'paragraph',
        text: 'Why duplicate the Redis client?',
      },
      {
        type: 'paragraph',
        text: 'Redis connections operating in Pub/Sub mode cannot be used normally for other commands.',
      },
      {
        type: 'paragraph',
        text: 'Creating a dedicated subscriber connection isolates Pub/Sub traffic from the rest of the application.',
      },
      {
        type: 'heading',
        text: 'Publishing Notifications',
      },
      {
        type: 'paragraph',
        text: 'After the worker persists the notification in PostgreSQL, it publishes an event.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'notification.worker.ts',
        code:
          'const payload = {\n' +
          '  id: uuidv4(),\n' +
          '  sender: data.sender,\n' +
          '  userId: data.userId,\n' +
          '  type: data.type,\n' +
          '  title: data.title,\n' +
          '  message: data.message,\n' +
          '  createdAt: new Date().toISOString(),\n' +
          '};\n\n' +
          'await prisma.notification.create({\n' +
          '  data: {\n' +
          '    fromUserId: Number(payload.sender),\n' +
          '    toUserId: Number(payload.userId),\n' +
          '    title: payload.title,\n' +
          '    message: payload.message,\n' +
          '  }\n' +
          '});\n\n' +
          'await redis.publish(\n' +
          '  "notifications",\n' +
          '  JSON.stringify(payload)\n' +
          ');',
      },
      {
        type: 'paragraph',
        text: 'Why store the notification before publishing?',
      },
      {
        type: 'paragraph',
        text: 'Persisting first guarantees durability.',
      },
      {
        type: 'paragraph',
        text: 'If a user is offline, notifications remain available and can later be retrieved using the REST API.',
      },
      {
        type: 'paragraph',
        text: 'Publishing after persistence ensures that no delivered notification is lost.',
      },
      {
        type: 'heading',
        text: 'Delivering Notifications to Connected Users',
      },
      {
        type: 'paragraph',
        text: 'Every application instance subscribes to Redis.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'sse.subscriber.ts',
        code:
          'await subscriber.subscribe(\n' +
          '  "notifications",\n' +
          '  (message) => {\n' +
          '    const payload = JSON.parse(message);\n' +
          '    const connections = clients.get(\n' +
          '      String(payload.userId)\n' +
          '    );\n' +
          '    if (!connections || connections.size === 0)\n' +
          '      return;\n\n' +
          '    const frame =\n' +
          '      `event: notification\\n` +\n' +
          '      `data: ${JSON.stringify(payload)}\\n\\n`;\n\n' +
          '    for (const client of connections) {\n' +
          '      client.res.write(frame);\n' +
          '    }\n' +
          '  }\n' +
          ');',
      },
      {
        type: 'paragraph',
        text: 'Why this approach?',
      },
      {
        type: 'list',
        items: [
          'Each server instance only knows about its local SSE connections.',
          'Redis broadcasts the event to every instance.',
          'Only the instance holding the user\'s connection actually sends the event.',
        ],
      },
      {
        type: 'paragraph',
        text: 'This architecture allows horizontal scaling without introducing sticky sessions or centralized connection management.',
      },
      {
        type: 'heading',
        text: 'Background Processing with BullMQ',
      },
      {
        type: 'paragraph',
        text: 'Notification delivery is executed asynchronously through BullMQ.',
      },
      {
        type: 'code',
        language: 'text',
        filename: 'notification-flow.txt',
        code:
          'User Action\n' +
          '      ↓\n' +
          'BullMQ Job\n' +
          '      ↓\n' +
          'Worker\n' +
          '      ↓\n' +
          'Database\n' +
          '      ↓\n' +
          'Redis Pub/Sub\n' +
          '      ↓\n' +
          'SSE',
      },
      {
        type: 'paragraph',
        text: 'Why use BullMQ?',
      },
      {
        type: 'list',
        items: [
          'Prevents request blocking.',
          'Improves API response times.',
          'Supports retries.',
          'Handles transient failures.',
          'Decouples business logic from delivery logic.',
        ],
      },
      {
        type: 'paragraph',
        text: 'A failed notification can be retried without affecting the user\'s original request.',
      },
      {
        type: 'heading',
        text: 'Hardening for Production',
      },
      {
        type: 'paragraph',
        text: 'The pipeline above is the version that ships first, and it\'s deliberately simple. As SRVJ grows past a single instance and starts retrying jobs under load, three refinements matter. None of them change the core idea — they make it correct at scale.',
      },
      {
        type: 'heading',
        text: 'Scaling the Fan-Out: Per-User Channels',
      },
      {
        type: 'paragraph',
        text: 'The version above publishes every notification to a single global notifications channel, and every instance subscribes to it. That\'s the simplest thing that works, and at a small number of instances it\'s completely fine.',
      },
      {
        type: 'paragraph',
        text: 'But notice what happens as you scale out: every instance receives every notification and then discards the ones it doesn\'t own. With N instances, roughly (N-1)/N of that fan-out is wasted CPU and network that grows with both notification volume and instance count.',
      },
      {
        type: 'paragraph',
        text: 'The refinement is per-user channels — notif:user:{id}. Each instance subscribes only to the users currently connected to it, and unsubscribes when the last tab for that user disconnects:',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'sse.channels.ts',
        code:
          '// on connect (first tab for this user on this instance)\n' +
          'await subscriber.subscribe(`notif:user:${userId}`, handleMessage);\n\n' +
          '// on disconnect (last tab gone)\n' +
          'await subscriber.unsubscribe(`notif:user:${userId}`);',
      },
      {
        type: 'paragraph',
        text: 'The publish side targets the user directly instead of broadcasting:',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'notification.worker.ts',
        code: 'await redis.publish(`notif:user:${payload.userId}`, JSON.stringify(payload));',
      },
      {
        type: 'paragraph',
        text: 'Now each instance receives only the messages for users it actually holds.',
      },
      {
        type: 'paragraph',
        text: 'Tradeoffs. You trade a fixed broadcast cost for subscribe/unsubscribe churn on every connect and disconnect, plus many short-lived channels in Redis. That\'s a good trade once instance count and notification volume grow; the single global channel is fine while you\'re small. Pick the per-user model the moment you horizontally scale the app tier in earnest.',
      },
      {
        type: 'heading',
        text: 'Idempotent Worker Writes',
      },
      {
        type: 'paragraph',
        text: 'BullMQ delivers at-least-once. A worker that crashes after writing to PostgreSQL but before acking the job will see that job again on restart — and a blind create produces a duplicate notification.',
      },
      {
        type: 'paragraph',
        text: 'The fix is a stable dedup key (the domain eventId, or a deterministic hash of type + sender + recipient + target) plus a unique constraint, so the second delivery becomes a no-op instead of a duplicate:',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'notification.worker.ts',
        code:
          'await prisma.notification.upsert({\n' +
          '  where: { eventId: payload.eventId },\n' +
          '  update: {},\n' +
          '  create: {\n' +
          '    eventId: payload.eventId,\n' +
          '    fromUserId: Number(payload.sender),\n' +
          '    toUserId: Number(payload.userId),\n' +
          '    title: payload.title,\n' +
          '    message: payload.message,\n' +
          '  },\n' +
          '});',
      },
      {
        type: 'paragraph',
        text: 'Tradeoff. You need a deterministic key and a unique column — a little schema discipline. And worth being honest: exactly-once across queue → DB → Redis doesn\'t really exist. Idempotent writes are how you approximate it, and they\'re non-negotiable the moment the consumer has side effects.',
      },
      {
        type: 'heading',
        text: 'Surviving Reconnections',
      },
      {
        type: 'paragraph',
        text: 'SSE auto-reconnects, but Redis Pub/Sub has no buffer: anything published while a client was disconnected is simply gone. Two ways to close that gap:',
      },
      {
        type: 'list',
        items: [
          'Refetch on reconnect — When EventSource fires onopen, the client calls the REST list endpoint (GET /notifications) to reconcile against PostgreSQL. This needs nothing extra and is the pragmatic default for SRVJ.',
          'Last-Event-ID replay — On reconnect the browser sends the Last-Event-ID header automatically, and the server replays what was missed. This requires a durable per-user log to replay from — which pushes you toward Redis Streams.',
        ],
      },
      {
        type: 'paragraph',
        text: 'For SRVJ, the refetch path wins: the durable store already exists, so the realtime layer is free to be lossy.',
      },
      {
        type: 'heading',
        text: 'Pub/Sub vs Redis Streams',
      },
      {
        type: 'paragraph',
        text: 'Redis Pub/Sub is fire-and-forget — no subscriber connected at publish time means the message is dropped, with no replay and no acknowledgement. That\'s acceptable here precisely because the REST list reconciles anything lost.',
      },
      {
        type: 'paragraph',
        text: 'If you ever need "no notification missed in realtime, even across reconnects, without a refetch," move the channel to Redis Streams (XADD + consumer groups + XACK). You get at-least-once delivery and replay via XRANGE, at the cost of a trimming policy (MAXLEN), consumer-group bookkeeping, and more memory. Reach for it only when the refetch model stops being good enough — not before.',
      },
      {
        type: 'heading',
        text: 'Why I Chose SSE',
      },
      {
        type: 'paragraph',
        text: 'For server-generated notifications, SSE provided:',
      },
      {
        type: 'list',
        items: [
          'Native browser support.',
          'Automatic reconnection.',
          'Simple architecture.',
          'Lower operational complexity.',
          'Lightweight server-to-client communication.',
          'Seamless integration with existing HTTP infrastructure.',
        ],
      },
      {
        type: 'paragraph',
        text: 'SSE is not a replacement for WebSockets, but for notification delivery in SRVJ, it turned out to be the right tool for the job.',
      },
      {
        type: 'paragraph',
        text: 'Next in the series: How CRDTs and Yjs power collaborative editing in SRVJ.',
      },
    ],
  },
  {
    id: 2,
    slug: 'paymob-amazon-payment-services-integration',
    title: 'PayMob, Amazon Payment Services',
    excerpt:
      'Months of integrating PayMob and Amazon Payment Services (PayFort) into a production marketplace • the adapter, payment state machine, and webhook pipeline',
    category: 'Payment Integration',
    date: '2026-06-12',
    readTime: '12 min read',
    tags: ['Payments', 'Paymob', 'Amazon Payment Services', 'PayFort', 'Webhooks', 'BullMQ', 'Node.js', 'TypeScript'],
    blocks: [
      {
        type: 'paragraph',
        text: 'I\'ve spent the last few months integrating two payment providers into a production marketplace: PayMob and Amazon Payment Services (the thing everyone still calls PayFort). The docs got me to my first sandbox transaction in an afternoon. Everything after that, I had to figure out the hard way.',
      },
      {
        type: 'paragraph',
        text: 'So this post is the writeup I wish existed when I started. It\'s not "how to call the PayMob API" — there are ten of those already and they all stop right before the part that hurts. This is about the architecture that sits between your Express app and two providers that disagree on basically everything.',
      },
      {
        type: 'paragraph',
        text: 'Fair warning: this assumes you\'re a backend engineer who\'s shipped things before. I\'m not going to explain what a webhook is.',
      },

      {
        type: 'heading',
        text: 'Two providers, one interface (or: how I stopped writing if-statements)',
      },
      {
        type: 'paragraph',
        text: 'My first version had `if (provider === \'paymob\')` checks scattered around. It worked for about two weeks. Then I needed refunds, and the branching got ugly fast, because these two providers genuinely agree on nothing:',
      },
      {
        type: 'list',
        items: [
          'PayMob auth is a three-step dance — authenticate, create an order, get a payment key. APS signs every single request with a signature you compute over the sorted request params plus a passphrase.',
          'PayMob webhooks come with an HMAC computed over a very specific ordering of fields concatenated together. APS sends a signature you recompute yourself with the same sorted-params scheme.',
          'PayMob wants amounts in piasters. APS wants the amount multiplied by the currency\'s decimal factor, which is different per currency. Yes, I got this wrong once.',
          '"Success" in PayMob is a boolean and a transaction object. In APS it\'s a numeric response code where the `14xxx` family means success and everything else means go check the table.',
        ],
      },
      {
        type: 'paragraph',
        text: 'So I pulled everything behind one internal interface: create intent, capture, refund, verify webhook, normalize status. One adapter per provider. The rest of the codebase has no idea PayMob exists.',
      },
      {
        type: 'paragraph',
        text: 'The payoff came faster than expected. APS merchant accounts are scoped to a single currency — something I learned when an EGP transaction went through a USD-configured account and failed in a way that made zero sense. The fix lived entirely inside the APS adapter. Nothing else in the system changed. That\'s the whole argument for the pattern, honestly.',
      },
      {
        type: 'paragraph',
        text: 'The catch: the shared interface is a lowest common denominator. PayMob has installment stuff, APS has tokenization quirks, and neither maps cleanly. You either keep growing the interface (it gets bloated) or you add a providerOptions passthrough and accept the leak. I went with the leak. A documented escape hatch beats pretending two different products are the same product.',
      },

      {
        type: 'heading',
        text: 'Payments are state machines whether you like it or not',
      },
      {
        type: 'paragraph',
        text: 'Early on, payment status was just a string field that any code path could update. Then a late PayMob retry arrived after my expiry job had already marked an intent as expired, flipped it back to success, and I spent an evening figuring out why an expired payment had sent a confirmation email.',
      },
      {
        type: 'paragraph',
        text: 'Now every intent goes through an actual state machine:',
      },
      {
        type: 'code',
        language: 'mermaid',
        filename: 'payment-intent-states.mmd',
        code:
          'stateDiagram-v2\n' +
          '    [*] --> CREATED\n' +
          '    CREATED --> PENDING: redirect to provider\n' +
          '    PENDING --> PROCESSING: webhook received\n' +
          '    PROCESSING --> SUCCEEDED: verified success\n' +
          '    PROCESSING --> FAILED: verified failure\n' +
          '    PENDING --> EXPIRED: TTL exceeded\n' +
          '    SUCCEEDED --> REFUND_PENDING: refund requested\n' +
          '    REFUND_PENDING --> REFUNDED: refund confirmed\n' +
          '    REFUND_PENDING --> SUCCEEDED: refund rejected\n' +
          '    FAILED --> [*]\n' +
          '    EXPIRED --> [*]\n' +
          '    REFUNDED --> [*]',
      },
      {
        type: 'paragraph',
        text: 'The rule is simple: transitions get validated at write time, with an atomic compare-and-set on the current state. A FAILED intent can\'t become SUCCEEDED no matter what shows up. An EXPIRED intent rejects everything. When two writers race — say, a webhook handler and a reconciliation job hitting the same intent milliseconds apart — the loser gets a rejected transition instead of silently winning by being last.',
      },
      {
        type: 'paragraph',
        text: 'A status field describes. A state machine enforces. That\'s the difference, and it only matters in exactly the moments when everything else is going wrong, which is exactly when you need it.',
      },
      {
        type: 'paragraph',
        text: 'The annoying part: now you have to handle legitimate out-of-order events explicitly. Under load, APS can deliver an authorization webhook after the capture webhook. The state machine forces you to sit down and decide what that means instead of letting the last write win. More design work up front. Way fewer 2 AM surprises.',
      },

      {
        type: 'heading',
        text: 'Webhooks: do almost nothing, fast',
      },
      {
        type: 'paragraph',
        text: 'Here\'s the mistake I see in nearly every integration tutorial: the webhook handler verifies the signature, updates the database, sends an email, updates inventory, and then returns 200. If anything in that chain is slow or throws, the provider retries, and now you\'ve processed the same payment twice. And PayMob retries aggressively. It will not be polite about it.',
      },
      {
        type: 'paragraph',
        text: 'What actually works:',
      },
      {
        type: 'code',
        language: 'mermaid',
        filename: 'webhook-pipeline.mmd',
        code:
          'sequenceDiagram\n' +
          '    participant P as Provider (PayMob / APS)\n' +
          '    participant W as Webhook Endpoint\n' +
          '    participant Q as BullMQ Queue\n' +
          '    participant J as Worker\n' +
          '    participant DB as MongoDB\n' +
          '    participant L as Ledger\n\n' +
          '    P->>W: POST webhook payload\n' +
          '    W->>W: Verify HMAC / signature (raw body)\n' +
          '    alt invalid signature\n' +
          '        W-->>P: 401\n' +
          '    else valid\n' +
          '        W->>Q: Enqueue, jobId = provider txn id\n' +
          '        W-->>P: 200 within milliseconds\n' +
          '    end\n' +
          '    Q->>J: Deliver job (deduped by jobId)\n' +
          '    J->>DB: Atomic state transition\n' +
          '    alt transition valid\n' +
          '        J->>L: Append ledger entry\n' +
          '        J->>Q: Enqueue side effects (email, inventory)\n' +
          '    else transition invalid\n' +
          '        J->>J: Log it, drop it\n' +
          '    end',
      },
      {
        type: 'paragraph',
        text: 'The endpoint does two things: cryptographic verification and enqueueing. That\'s it. Everything else happens in a BullMQ worker.',
      },
      {
        type: 'paragraph',
        text: 'Verification stays synchronous and happens against the raw body, before you trust a single field in the payload. If you enqueue unverified payloads, congratulations, your queue is now an attack surface.',
      },
      {
        type: 'paragraph',
        text: 'The trick I like most here: use the provider\'s transaction ID as the BullMQ job ID. BullMQ dedupes jobs with the same ID, so PayMob\'s retry storm collapses into one job before your handler logic even runs. Idempotency at the queue layer, basically free.',
      },
      {
        type: 'paragraph',
        text: 'There is a real cost, though. Returning 200 now means "received and verified," not "processed." If the worker dies permanently, the provider walks away believing delivery succeeded, and nobody retries anything. That gap is exactly why reconciliation exists — more on that below. I considered going back to synchronous processing once or twice, but coupling your webhook response time to your slowest side effect is a worse deal in every scenario I could come up with.',
      },

      {
        type: 'heading',
        text: 'The outbound side: don\'t trust your own retries either',
      },
      {
        type: 'paragraph',
        text: 'Webhooks cover inbound duplicates. But your own server retrying a capture or refund after a timeout is just as dangerous, and nobody talks about it.',
      },
      {
        type: 'paragraph',
        text: 'The scenario: you call the APS refund API, it times out. Did the refund go through? You genuinely don\'t know. Their behavior under timeout is ambiguous. Retry blindly and you might refund twice — and explaining a double refund to finance is a conversation I\'d like to never have.',
      },
      {
        type: 'paragraph',
        text: 'So before any provider call, I write an operation record keyed by a deterministic idempotency key: intent ID plus operation type plus attempt scope. The retry path checks that record first, then queries the provider for the operation\'s actual status before re-issuing anything. It turns "did I just double-refund someone" from a panic into a database query.',
      },
      {
        type: 'paragraph',
        text: 'Cost: more writes, more state, and you need a cleanup policy for stale records. Cheap insurance.',
      },

      {
        type: 'heading',
        text: 'The ledger, or: your database will lie to you eventually',
      },
      {
        type: 'paragraph',
        text: 'The intent record answers "what is the state right now." It cannot answer "what happened, in what order, according to whom." For that I keep an append-only ledger — every event is a new immutable row referencing the intent. Webhook received? Row. Transition applied? Row. Reconciliation corrected something? Row, tagged as such.',
      },
      {
        type: 'paragraph',
        text: 'The first time PayMob\'s dashboard and my database disagreed about a transaction, the ledger was how I reconstructed what actually happened. Mutable state tells you where you ended up. The ledger tells you how you got there. It\'s also the thing your finance team actually wants when they audit — not the current status, the history.',
      },
      {
        type: 'paragraph',
        text: 'And no, the provider\'s dashboard doesn\'t replace this. Providers prune, paginate, and occasionally revise their own records. The ledger is the only record you control.',
      },
      {
        type: 'paragraph',
        text: 'Could I have gone full event sourcing and derived all state from events? Sure. But replaying events to answer "what\'s the current status" is a lot of machinery for a payments subsystem. The hybrid — intent record for current state, ledger for history — is the pragmatic middle ground, and I haven\'t regretted it.',
      },

      {
        type: 'heading',
        text: 'Reconciliation: the job that catches everyone else\'s mistakes',
      },
      {
        type: 'paragraph',
        text: 'Every layer above has some narrow failure window. A webhook lost after the 200. A worker crash mid-transition. The provider revising a status on their side. Reconciliation is the scheduled job that sweeps up after all of them:',
      },
      {
        type: 'list',
        items: [
          'Pull intents stuck in non-terminal states past a threshold.',
          'Hit the provider\'s transaction inquiry API for ground truth.',
          'Apply corrections through the state machine — no backdoors, corrections are transitions like everything else.',
          'Write a ledger entry tagged as reconciliation-sourced.',
          'Alert on anything it can\'t resolve on its own.',
        ],
      },
      {
        type: 'paragraph',
        text: 'Why pull-based inquiry instead of trusting webhook retries? Because webhook delivery is at-least-once in theory and at-most-once whenever the provider is having a bad day. The inquiry API doesn\'t depend on their delivery infrastructure being healthy.',
      },
      {
        type: 'paragraph',
        text: 'Two things to watch. Inquiry APIs are rate-limited, so the job needs cursor pagination and backoff — don\'t hammer them. And the sneaky one: reconciliation can mask upstream bugs. If it\'s quietly fixing hundreds of intents a day, your webhook pipeline is broken and the job is hiding the evidence. I track the correction rate as a health metric. The day it spikes, something upstream broke.',
      },

      {
        type: 'heading',
        text: 'The stuff that actually bit me',
      },
      {
        type: 'paragraph',
        text: 'Quick field notes, because every comparison post out there stops at a pricing table:',
      },
      {
        type: 'list',
        items: [
          'PayMob\'s HMAC field ordering — the HMAC is computed over a specific concatenation of fields, including booleans serialized as lowercase strings. Get one field wrong and every webhook fails verification with an error message that tells you absolutely nothing. I lost real hours to this.',
          'APS currency-scoped merchant accounts — one account, one currency. Multi-currency means multiple accounts and routing logic in your adapter. Find this out before launch. I almost didn\'t.',
          'Refunds are where the bugs live — PayMob refunds reference the original transaction directly. APS refunds are brand-new operations with their own signature computation and their own response-code space. Whatever time you budgeted for refund testing, double it.',
          'Both sandboxes lie, differently — APS sandbox response codes don\'t cover the full production failure space. PayMob\'s sandbox webhook timing is much gentler than production retry behavior. Fire synthetic duplicate webhooks at your own endpoint before going live — production will do it for you otherwise, at a worse time.',
        ],
      },

      {
        type: 'heading',
        text: 'Wrapping up',
      },
      {
        type: 'paragraph',
        text: 'Nothing here is exotic. Adapters, state machines, queues, ledgers, a reconciliation job — you\'ve seen all of these before. What took me a while to internalize is that payments need all of them at once, because each one covers a failure mode the others can\'t reach. Skip the adapter and provider quirks spread through your codebase. Skip the state machine and races corrupt your data. Skip verify-then-enqueue and retries double-process. Skip the ledger and you can\'t audit anything. Skip reconciliation and every gap above turns into silent data loss.',
      },
      {
        type: 'paragraph',
        text: 'Build all five and something nice happens: PayMob and APS stop being a source of incidents and become what payment infrastructure should be — boring.',
      },
      {
        type: 'paragraph',
        text: 'If you\'ve integrated either of these and hit something I didn\'t cover, I\'d genuinely like to hear about it.',
      },
    ],
  },
  {
    id: 1,
    slug: 'jwt-vs-paseto-tokens',
    title: 'JWT vs PASETO',
    excerpt:
      'I have shipped JWT in production, gotten burned by it, switched to PASETO for auth and payments, and learned that most teams never question the default.',
    category: 'Backend Security',
    date: '2026-05-12',
    readTime: '14 min read',
    tags: ['Security', 'JWT', 'PASETO', 'Auth', 'Tokens', 'Node.js', 'TypeScript'],
    blocks: [
      {
        type: 'paragraph',
        text: 'Let me be upfront about something: the way I handle tokens in my own backends is not what most teams do. I use PASETO for both auth and payment tokens. Most of the industry uses JWT for everything. This post is my honest take on why I made that switch, what the real tradeoffs are, and — more importantly — what token format you choose matters far less than whether you are using the right type of token for the job at all.',
      },
      {
        type: 'paragraph',
        text: 'This is my opinion. JWT is not wrong. If your team is already on JWT, uses a maintained library, and has proper algorithm enforcement in place, you are fine. I am not here to tell you to migrate. I am here to explain the reasoning behind my choices and let you decide if any of it applies to your situation.',
      },

      {
        type: 'heading',
        text: 'First, understand what you are actually issuing',
      },
      {
        type: 'paragraph',
        text: 'A token is a portable claim. You encode some data, sign or encrypt it, hand it to a client, and trust it when you see it again — without calling a database. That last part is why tokens are so appealing. It is also why they cause so much damage when misused.',
      },
      {
        type: 'paragraph',
        text: 'There are three fundamentally different things people call "tokens" and they are not interchangeable:',
      },
      {
        type: 'list',
        items: [
          'Signed tokens — the payload is readable by anyone. You are only proving it was not tampered with. JWT (JWS) and PASETO v4.public both fall here.',
          'Encrypted tokens — the payload is hidden. Only someone with the key can read it. JWE and PASETO v4.local fall here.',
          'Opaque tokens — a random string with no embedded claims. You must hit a database to know what it means.',
        ],
      },
      {
        type: 'paragraph',
        text: 'Most developers only know the first category. That is the root of every token security problem I have seen.',
      },

      {
        type: 'heading',
        text: 'JWT — what it actually does well',
      },
      {
        type: 'paragraph',
        text: 'JWT is everywhere because it genuinely solved a real problem at the right moment. When OAuth 2.0 and OpenID Connect became the standard handshake between services, having a universal, self-describing token format was essential. Every API gateway, every identity provider, every load balancer, every auth library in every language understands JWT. That interoperability is not something you throw away lightly — and for most teams, it is the reason JWT is the correct default.',
      },
      {
        type: 'paragraph',
        text: 'Asymmetric JWT — signed with ES256 specifically — works well for distributed systems. Your auth service holds the private key and signs tokens. Every other service holds the public key and verifies them. No shared secret, no service-to-service trust dependency. The JWKS endpoint makes public key discovery and rotation automatic. This is a genuinely well-designed system.',
      },
      {
        type: 'list',
        items: [
          'Universal support — OAuth, OIDC, AWS Cognito, Auth0, Okta, every API gateway. JWT is the lingua franca and that matters.',
          'Asymmetric signing — services verify without holding the signing key.',
          'JWKS — automatic public key discovery and rotation over HTTP. Nothing in the PASETO world has an equivalent.',
          'Standardised claims — iss, sub, aud, exp, iat, jti. Every library validates them.',
          'Tooling — jwt.io, debug middleware, framework plugins. Fifteen years of ecosystem depth.',
        ],
      },

      {
        type: 'heading',
        text: 'JWT — where it gets teams into trouble',
      },
      {
        type: 'paragraph',
        text: 'The JWT spec made one decision that has caused an outsized amount of damage: the signing algorithm is declared inside the token header, by the client. The server is supposed to enforce its own expected algorithm. In practice, many libraries historically did not do that by default. The result was the alg: none attack and the algorithm confusion attack — both of which should not have been possible if the spec had made different choices.',
      },
      {
        type: 'paragraph',
        text: 'These vulnerabilities are largely a 2015 story if you are using a maintained library today. But the underlying design is still there. Algorithm safety in JWT is a code review discipline. You need to remember to set the algorithms allowlist. You need to review every new developer\'s auth middleware. You need library upgrades to not introduce regressions. It is manageable — most production JWT systems are fine — but it is discipline-dependent rather than structurally enforced.',
      },
      {
        type: 'list',
        items: [
          'alg: none attack — declare no algorithm, strip the signature, submit. Fixed in modern libraries but the design is still a footgun.',
          'Algorithm confusion — RS256 server tricked into accepting HS256 where the "secret" is the public key. Same root cause.',
          'Sensitive payload — JWT is signed, not encrypted. The payload is base64url. Anyone who intercepts the token reads your claims. This is the one that surprises junior developers the most.',
          'Long expiry — access tokens set to 24 hours or more because "users hate logging in". Irrevocable without a blocklist you never built.',
        ],
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'jwt.what-not-to-do.ts',
        code:
          '// Real mistakes I have seen in production codebases.\n\n' +
          '// 1. No algorithm enforcement\n' +
          'jwt.verify(token, secret)\n' +
          '// The library accepts whatever alg the token header claims.\n\n' +
          '// 2. Reading claims before verification\n' +
          'const { userId } = JSON.parse(\n' +
          '  Buffer.from(token.split(".")[1], "base64url").toString()\n' +
          ')\n' +
          '// You just trusted an unverified token.\n\n' +
          '// 3. Sensitive data in a signed (not encrypted) token\n' +
          'jwt.sign({ userId, email, plan: "enterprise", cardLastFour: "4242" }, secret)\n' +
          '// base64url is not encryption. Anyone with the token reads this.\n\n' +
          '// 4. HS256 with a weak secret\n' +
          'const secret = process.env.JWT_SECRET ?? "dev-secret"\n' +
          '// Offline brute-forceable from any captured token.\n',
      },
      {
        type: 'paragraph',
        text: 'The correct version of JWT auth is not complicated — it just requires deliberate choices:',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'jwt.done-right.ts',
        code:
          "import jwt from 'jsonwebtoken'\n" +
          "import { readFileSync } from 'fs'\n\n" +
          'const privateKey = readFileSync("./keys/ec-private.pem")\n' +
          'const publicKey  = readFileSync("./keys/ec-public.pem")\n\n' +
          'export interface AuthTokenPayload {\n' +
          '  sub:       string\n' +
          '  role:      string\n' +
          '  sessionId: string\n' +
          '  jti:       string\n' +
          '}\n\n' +
          'export function signAuthToken(payload: Omit<AuthTokenPayload, "jti">): string {\n' +
          '  return jwt.sign(\n' +
          '    { ...payload, jti: crypto.randomUUID() },\n' +
          '    privateKey,\n' +
          '    {\n' +
          '      algorithm: "ES256",\n' +
          '      expiresIn:  "15m",\n' +
          '      issuer:    "api.example.com",\n' +
          '      audience:  "web-client",\n' +
          '    }\n' +
          '  )\n' +
          '}\n\n' +
          'export function verifyAuthToken(token: string): AuthTokenPayload {\n' +
          '  return jwt.verify(token, publicKey, {\n' +
          '    algorithms: ["ES256"],   // allowlist — this line is mandatory\n' +
          '    issuer:    "api.example.com",\n' +
          '    audience:  "web-client",\n' +
          '  }) as AuthTokenPayload\n' +
          '}\n',
      },

      {
        type: 'heading',
        text: 'PASETO — why I switched and what it actually fixes',
      },
      {
        type: 'paragraph',
        text: 'I want to be clear: I use PASETO in my own stack. This is not the industry standard and I am not claiming it should be. Most production systems run JWT and they are fine. But when I was building a backend where I controlled every service end to end, I chose PASETO for auth and payments — and here is why.',
      },
      {
        type: 'paragraph',
        text: 'The version and purpose are baked into the token prefix — v4.public, v4.local. A server that calls V4.verify() will only ever process a v4.public token signed with Ed25519. There is no alg field. There is no negotiation. You cannot misconfigure it into an algorithm confusion vulnerability because the footgun literally does not exist in the API. That is the structural guarantee JWT cannot give you.',
      },
      {
        type: 'paragraph',
        text: 'For auth tokens I use PASETO v4.public — Ed25519 signed. It is faster than RSA, the keys are smaller, and the API has one right way to use it. For payment tokens I use PASETO v4.local — XChaCha20-Poly1305 encrypted. Real encryption, not base64. The implicit assertion feature lets me bind the token to the authenticated user ID at the encryption layer, not just as a claim in the payload.',
      },
      {
        type: 'list',
        items: [
          'Algorithm safety by design — version prefix is the algorithm contract. No runtime negotiation, no discipline required.',
          'v4.public uses Ed25519 — faster than RS256, smaller keys than RSA-2048, same asymmetric trust model.',
          'v4.local = real encryption — XChaCha20-Poly1305 authenticated encryption. Payload is ciphertext, not encoded text.',
          'Implicit assertions — bind a token cryptographically to external context without embedding it in the payload.',
          'Simpler API — fewer options means fewer wrong choices.',
        ],
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'paseto.auth.ts',
        code:
          "import { V4 } from 'paseto'\n\n" +
          '// const { secretKey, publicKey } = await V4.generateKey("public", { format: "paserk" })\n\n' +
          'const secretKey = process.env.PASETO_SECRET_KEY!\n' +
          'const publicKey = process.env.PASETO_PUBLIC_KEY!\n\n' +
          'export interface AuthTokenPayload {\n' +
          '  sub:       string\n' +
          '  role:      string\n' +
          '  sessionId: string\n' +
          '}\n\n' +
          'export async function signAuthToken(\n' +
          '  payload: AuthTokenPayload\n' +
          '): Promise<string> {\n' +
          '  return V4.sign(\n' +
          '    { ...payload, iss: "api.example.com", aud: "web-client" },\n' +
          '    secretKey,\n' +
          '    { expiresIn: "15 minutes" }\n' +
          '  )\n' +
          '}\n\n' +
          'export async function verifyAuthToken(\n' +
          '  token: string\n' +
          '): Promise<AuthTokenPayload> {\n' +
          '  const payload = await V4.verify(token, publicKey, {\n' +
          '    issuer:         "api.example.com",\n' +
          '    audience:       "web-client",\n' +
          '    clockTolerance: "1 minute",\n' +
          '  })\n' +
          '  return payload as AuthTokenPayload\n' +
          '}\n',
      },

      {
        type: 'heading',
        text: 'PASETO — the honest reasons most teams do not use it',
      },
      {
        type: 'paragraph',
        text: 'The technical case for PASETO is solid. The adoption reality is not. The main reason most teams stay on JWT has nothing to do with JWT being better — it is ecosystem lock-in. OAuth 2.0, OpenID Connect, AWS Cognito, Auth0, Okta, every API gateway and third-party identity provider speaks JWT. None of them speak PASETO. If you need to integrate with any of those, you are using JWT whether you like it or not.',
      },
      {
        type: 'paragraph',
        text: 'The other barrier is that PASETO is simply not well known. Most developers learned tokens through JWT tutorials. They have never heard of PASETO. The ecosystem is smaller, the tooling is thinner, and when something breaks in production at 2am there are fewer Stack Overflow answers. That is a real cost.',
      },
      {
        type: 'list',
        items: [
          'No OAuth / OIDC support — every major IdP speaks JWT. If you need third-party auth integration, PASETO is not an option.',
          'No JWKS equivalent — public key discovery is something you build yourself. JWT solved this years ago.',
          'v4.local key distribution — symmetric key needs to reach every decrypting service. Wider key distribution = wider blast radius.',
          'Small ecosystem — fewer libraries, fewer developers with production experience, less tooling.',
          'Switching cost — teams already on JWT have working systems. Migrating for a structural improvement is a hard sell.',
        ],
      },
      {
        type: 'paragraph',
        text: 'I use PASETO because I built systems from scratch where I controlled every service and had no third-party IdP requirements. If your situation is different — and for most teams it is — JWT done properly is the right call.',
      },

      {
        type: 'heading',
        text: 'The more important conversation — token taxonomy',
      },
      {
        type: 'paragraph',
        text: 'JWT vs PASETO is honestly the less interesting debate. The damage I see most often in production is not teams using the wrong format — it is teams using the right format for the wrong job. A signed stateless token used where an opaque revocable one was needed. That mistake costs you regardless of whether the token is JWT or PASETO.',
      },

      {
        type: 'heading',
        text: 'Auth tokens — short-lived, asymmetrically signed',
      },
      {
        type: 'paragraph',
        text: 'I use PASETO v4.public here. Most teams use JWT ES256. Both are valid if done correctly — 15 minutes maximum, asymmetric signing, no sensitive data in the payload, a jti for revocation. The difference is structural vs disciplinary algorithm safety. Pick whichever fits your stack.',
      },
      {
        type: 'list',
        items: [
          'JWT ES256 if you need OAuth / OIDC / third-party IdP integration.',
          'PASETO v4.public if you own the full stack and want algorithm safety by construction.',
          '15 minute expiry. Not one hour. Not one day.',
          'Payload: sub, role, sessionId. Nothing you would be embarrassed to see in a log.',
        ],
      },

      {
        type: 'heading',
        text: 'Refresh tokens — opaque, always',
      },
      {
        type: 'paragraph',
        text: 'This one is not a matter of opinion. Refresh tokens should not be JWT. They should not be PASETO. They should be a cryptographically random string stored as a hashed row in your database. The entire point of a refresh token is that you can revoke it. A stateless token cannot be revoked without a blocklist, and if you need a blocklist you have already defeated the purpose of going stateless. Use the database.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'refresh-token.service.ts',
        code:
          "import crypto from 'crypto'\n\n" +
          'export function generateRefreshToken() {\n' +
          '  const raw    = crypto.randomBytes(48).toString("base64url")\n' +
          '  const hashed = crypto.createHash("sha256").update(raw).digest("hex")\n' +
          '  return { raw, hashed }\n' +
          '  // Store hashed in DB. Send raw to client via HttpOnly Secure cookie.\n' +
          '  // You will never see the raw value again — just like a password.\n' +
          '}\n\n' +
          '// On rotation: delete the old row, insert a new one.\n' +
          '// If a rotated token comes back in, that is a replay — revoke the session immediately.\n',
      },

      {
        type: 'heading',
        text: 'Payment tokens — encrypted, always',
      },
      {
        type: 'paragraph',
        text: 'This is where I feel most strongly. Payment tokens carry order amounts, PSP card tokens, idempotency keys, merchant references. They should be encrypted — not signed. Most teams sign a JWT with the payment details in the payload and call it done. That payload is base64url. It is not encrypted. Anyone who captures that token in transit, in a log, or in a browser history can read exactly what is in it.',
      },
      {
        type: 'paragraph',
        text: 'I use PASETO v4.local here. The payload is XChaCha20-Poly1305 encrypted. Only the payment service holds the symmetric key. The implicit assertion binds the token to the authenticated user ID at the encryption layer — not as a claim in the payload, but mixed into the encryption itself. If someone extracts a payment token and tries to use it in a different user\'s session, the decryption fails. Not an authorization check that can be bypassed — a cryptographic failure.',
      },
      {
        type: 'paragraph',
        text: 'To be honest: most backends do not need this level of precision. But payment data is the highest-value target in most systems and the cost of doing it properly is low once you understand the API.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'payment-token.service.ts',
        code:
          "import { V4 } from 'paseto'\n\n" +
          '// This key lives ONLY in the payment service.\n' +
          '// Not in the API gateway. Not in the order service. Only here.\n' +
          'const paymentKey = process.env.PASETO_PAYMENT_LOCAL_KEY!\n\n' +
          'export interface PaymentTokenPayload {\n' +
          '  orderId:        string\n' +
          '  userId:         string\n' +
          '  amount:         number\n' +
          '  currency:       string\n' +
          '  pspCardToken:   string  // PSP-issued token. Not the raw card number. Ever.\n' +
          '  idempotencyKey: string\n' +
          '}\n\n' +
          'export async function issuePaymentToken(\n' +
          '  payload: PaymentTokenPayload\n' +
          '): Promise<string> {\n' +
          '  return V4.encrypt(\n' +
          '    { ...payload, iss: "payment-service", aud: "payment-service" },\n' +
          '    paymentKey,\n' +
          '    {\n' +
          '      expiresIn: "5 minutes",\n' +
          '      // Mixed into the encryption — not a payload claim.\n' +
          '      // Wrong userId = cryptographic failure, not an authorization check.\n' +
          '      assertion: Buffer.from(payload.userId),\n' +
          '    }\n' +
          '  )\n' +
          '}\n\n' +
          'export async function consumePaymentToken(\n' +
          '  token:  string,\n' +
          '  userId: string  // from the verified auth token\n' +
          '): Promise<PaymentTokenPayload> {\n' +
          '  const payload = await V4.decrypt(token, paymentKey, {\n' +
          '    issuer:    "payment-service",\n' +
          '    audience:  "payment-service",\n' +
          '    assertion: Buffer.from(userId),\n' +
          '  })\n' +
          '  return payload as PaymentTokenPayload\n' +
          '}\n',
      },

      {
        type: 'heading',
        text: 'API keys — prefixed opaque strings',
      },
      {
        type: 'paragraph',
        text: 'API keys need to be revocable instantly. That requires a database row. Stripe figured this out years ago — a prefixed random string (sk_live_, sk_test_), shown once, stored hashed, looked up on every request. Not clever, but correct. JWT and PASETO are the wrong tools here.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'api-key.service.ts',
        code:
          "import crypto from 'crypto'\n\n" +
          "type KeyEnv = 'live' | 'test'\n\n" +
          'export function generateApiKey(env: KeyEnv) {\n' +
          '  const prefix = env === "live" ? "sk_live" : "sk_test"\n' +
          '  const secret = crypto.randomBytes(32).toString("base64url")\n' +
          '  const raw    = `${prefix}_${secret}`\n' +
          '  const hashed = crypto.createHash("sha256").update(raw).digest("hex")\n' +
          '  // Store: { hashed, prefix, scopes, createdAt, lastUsedAt }\n' +
          '  // Return raw once. After this moment it is gone from your system.\n' +
          '  return { raw, hashed, prefix }\n' +
          '}\n\n' +
          'export async function verifyApiKey(\n' +
          '  raw: string,\n' +
          '  db: { findByHash: (h: string) => Promise<{ scopes: string[] } | null> }\n' +
          ') {\n' +
          '  const hashed = crypto.createHash("sha256").update(raw).digest("hex")\n' +
          '  const record = await db.findByHash(hashed)\n' +
          '  if (!record) throw new Error("Invalid API key")\n' +
          '  return record\n' +
          '}\n',
      },

      {
        type: 'heading',
        text: 'Email verification and password reset — also opaque',
      },
      {
        type: 'paragraph',
        text: 'I have seen teams use JWT for password reset links. The argument is "stateless, no database needed." The problem: if a user requests five reset emails, all five tokens are valid until exp. No single-use enforcement, no way to invalidate them when the password changes, no way to expire them early. A random string in a database row, deleted on use. That is it.',
      },
      {
        type: 'list',
        items: [
          '32 bytes of crypto.randomBytes, stored hashed in the DB.',
          'Expiry in the DB row, not the token. You can change it without reissuing.',
          'Delete on successful use. Single-use by default.',
          'Rate-limit issuance — one per user per 5 minutes at minimum.',
        ],
      },

      {
        type: 'heading',
        text: 'Revocation — neither format solves this',
      },
      {
        type: 'paragraph',
        text: 'A stateless token is valid until exp. JWT or PASETO — makes no difference. A user logs out, changes their password, gets suspended — the token does not care. The pragmatic answer is a Redis blocklist keyed by jti with a TTL equal to the token\'s remaining lifetime. One sub-millisecond read per request. Acceptable cost for real-time revocation.',
      },
      {
        type: 'code',
        language: 'ts',
        filename: 'token-blocklist.ts',
        code:
          "import { Redis } from 'ioredis'\n\n" +
          'const redis = new Redis(process.env.REDIS_URL!)\n\n' +
          'export async function revokeToken(\n' +
          '  jti:       string,\n' +
          '  expiresAt: number\n' +
          '): Promise<void> {\n' +
          '  const ttl = expiresAt - Math.floor(Date.now() / 1000)\n' +
          '  if (ttl > 0) {\n' +
          '    await redis.set(`bl:${jti}`, "1", "EX", ttl)\n' +
          '  }\n' +
          '}\n\n' +
          'export async function isRevoked(jti: string): Promise<boolean> {\n' +
          '  return (await redis.exists(`bl:${jti}`)) === 1\n' +
          '}\n',
      },

      {
        type: 'heading',
        text: 'The decision matrix',
      },
      {
        type: 'list',
        items: [
          'Auth / access token → PASETO v4.public (my choice) or JWT ES256 (industry standard). 15 min. Both valid.',
          'Refresh token → Opaque random string, hashed in DB. Not negotiable.',
          'Payment token → PASETO v4.local (my choice). Encrypted, 5 min, implicit assertion. Most teams use signed JWT — that is the weaker option.',
          'API key → Prefixed opaque string, hashed in DB. Revocable, scoped, shown once.',
          'Email verification / password reset → Opaque random string, hashed in DB. Delete on use.',
          'Service-to-service → JWT ES256 with short expiry and explicit aud per target service.',
        ],
      },

      {
        type: 'heading',
        text: 'What I actually think',
      },
      {
        type: 'paragraph',
        text: 'JWT done properly is not dangerous. ES256, explicit algorithm enforcement, 15 minute expiry, no sensitive payload data, a jti, and a JWKS endpoint — that is a solid foundation and it is what most well-run teams have. The algorithm confusion vulnerabilities are mostly a historical story at this point if you are on a maintained library.',
      },
      {
        type: 'paragraph',
        text: 'I use PASETO because I prefer the algorithm safety to be structural rather than something I have to enforce through code review. And I use PASETO v4.local for payments because payment data should be encrypted, not just signed, and the implicit assertion gives me a cryptographic binding I cannot get from JWT without reaching for JWE — which is a significantly more complex spec.',
      },
      {
        type: 'paragraph',
        text: 'But this is my stack, my choice, and my opinion. PASETO adoption is low not because JWT is better but because switching costs are real and most teams are not in greenfield territory. If you are starting fresh and you own the whole system, I think PASETO is the cleaner choice. If you are integrating with third-party identity providers, you are using JWT and that is fine.',
      },
      {
        type: 'paragraph',
        text: 'Either way — the format is the smaller decision. The bigger one is whether you are using a signed stateless token for a job that needs an opaque revocable one. Refresh tokens that are JWT. Password reset links that are JWT. API keys that are JWT. Get the taxonomy right first. Then worry about JWT vs PASETO.',
      },
    ],
  },
]

export const getBlogBySlug = (slug: string) => blogs.find((blog) => blog.slug === slug)
