
export const spotifyPlaylist: any = [
    {
        id: 1,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/playlist/1wNirTC24xxOGVDAKf9sXu?utm_source=generator",
        width:"100%", 
        height:"352", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 2,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/playlist/1NeELYrxr2fBVK3g0bTqOz?utm_source=generator",
        width:"100%", 
        height:"352", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    }
]

export const spotifySongs: any = [
    {
        id: 1,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/2EEeOnHehOozLq4aS0n6SL?utm_source=generator",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 2,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/5qGHMDEUWSn8vVRyIgGXTi?utm_source=generator&theme=0",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 3,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/6IZF8hi9J6EtFDLQqOlSbu?utm_source=generator",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 4,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/6AYYPeG0IPbChi3Ts2jsrF?utm_source=generator",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 5,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/0jpsHPcR0o236aBU8SnCKG?utm_source=generator",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 6,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/7i2DJ88J7jQ8K7zqFX2fW8?utm_source=generator",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 7,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/7xSNmARgtbYjg9KqB4QA8P?utm_source=generator",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
    {
        id: 7,
        class: "rounded-xl shadow-lg",
        src: "https://open.spotify.com/embed/track/2PgDTvaEECeVZIhsuOF2Mc?utm_source=generator",
        width:"100%", 
        height:"152", 
        frameBorder:"0", 
        allow:"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture", 
        loading:"lazy",
    },
]